# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name ProscenioElement extends Resource

# Discriminated union dispatcher. Inspect the input dictionary's
# `type` key and delegate to the matching variant
# class. Used by the importer when building child elements/layers from
# the parsed JSON document.


static func from_dict(data: Dictionary) -> ProscenioElement:
	var tag: String = String(data.get("type", "mesh"))
	if tag == "mesh":
		return ProscenioMeshElement.from_dict(data)
	if tag == "sprite":
		return ProscenioSpriteElement.from_dict(data)
	push_error("unknown ProscenioElement tag: " + tag)
	return null
