# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name ProscenioSprite extends Resource

# Discriminated union dispatcher. Inspect the input dictionary's
# `type` key and delegate to the matching variant
# class. Used by the importer when building child sprites/layers from
# the parsed JSON document.


static func from_dict(data: Dictionary) -> ProscenioSprite:
	var tag: String = String(data.get("type", "polygon"))
	if tag == "polygon":
		return ProscenioPolygonSprite.from_dict(data)
	if tag == "sprite_frame":
		return ProscenioSpriteFrameSprite.from_dict(data)
	push_error("unknown ProscenioSprite tag: " + tag)
	return null
