# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name ProscenioKey extends Resource

# Names of fields actually set during `from_dict`. Lets consumers
# distinguish 'field set to default' from 'field absent in source'
# without re-parsing the JSON dictionary.
@export var _set_fields: PackedStringArray = PackedStringArray()
@export var time: float = 0.0
@export var interp: String = "linear"
@export var position: PackedFloat32Array = PackedFloat32Array()
@export var rotation: float = 0.0
@export var scale: PackedFloat32Array = PackedFloat32Array()
@export var frame: int = 0
@export var attachment: String = ""
@export var visible: bool = false


static func from_dict(data: Dictionary) -> ProscenioKey:
	var res := ProscenioKey.new()
	if data.has("time") and data["time"] != null:
		res.time = float(data["time"])
		res._set_fields.append("time")
	if data.has("interp") and data["interp"] != null:
		res.interp = String(data["interp"])
		res._set_fields.append("interp")
	if data.has("position") and data["position"] != null:
		res.position = PackedFloat32Array(data["position"])
		res._set_fields.append("position")
	if data.has("rotation") and data["rotation"] != null:
		res.rotation = float(data["rotation"])
		res._set_fields.append("rotation")
	if data.has("scale") and data["scale"] != null:
		res.scale = PackedFloat32Array(data["scale"])
		res._set_fields.append("scale")
	if data.has("frame") and data["frame"] != null:
		res.frame = int(data["frame"])
		res._set_fields.append("frame")
	if data.has("attachment") and data["attachment"] != null:
		res.attachment = String(data["attachment"])
		res._set_fields.append("attachment")
	if data.has("visible") and data["visible"] != null:
		res.visible = bool(data["visible"])
		res._set_fields.append("visible")
	return res
