# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name ProscenioSpriteFrameLayer extends ProscenioLayer

# Names of fields actually set during `from_dict`. Lets consumers
# distinguish 'field set to default' from 'field absent in source'
# without re-parsing the JSON dictionary.
@export var _set_fields: PackedStringArray = PackedStringArray()
@export var kind: String = "sprite_frame"
@export var name: String = ""
@export var position: PackedInt32Array = PackedInt32Array()
@export var size: PackedInt32Array = PackedInt32Array()
@export var z_order: int = 0
@export var frames: Array[ProscenioFrameEntry] = [] as Array[ProscenioFrameEntry]
@export var origin: PackedInt32Array = PackedInt32Array()
@export var blend_mode: String = "normal"
@export var subfolder: String = ""


static func from_dict(data: Dictionary) -> ProscenioSpriteFrameLayer:
	var res := ProscenioSpriteFrameLayer.new()
	if data.has("kind") and data["kind"] != null:
		res.kind = String(data["kind"])
		res._set_fields.append("kind")
	if data.has("name") and data["name"] != null:
		res.name = String(data["name"])
		res._set_fields.append("name")
	if data.has("position") and data["position"] != null:
		res.position = PackedInt32Array(data["position"])
		res._set_fields.append("position")
	if data.has("size") and data["size"] != null:
		res.size = PackedInt32Array(data["size"])
		res._set_fields.append("size")
	if data.has("z_order") and data["z_order"] != null:
		res.z_order = int(data["z_order"])
		res._set_fields.append("z_order")
	if data.has("frames") and data["frames"] != null:
		res.frames = ProscenioParseHelpers._parse_array(ProscenioFrameEntry, data["frames"])
		res._set_fields.append("frames")
	if data.has("origin") and data["origin"] != null:
		res.origin = PackedInt32Array(data["origin"])
		res._set_fields.append("origin")
	if data.has("blend_mode") and data["blend_mode"] != null:
		res.blend_mode = String(data["blend_mode"])
		res._set_fields.append("blend_mode")
	if data.has("subfolder") and data["subfolder"] != null:
		res.subfolder = String(data["subfolder"])
		res._set_fields.append("subfolder")
	return res
