# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.
@tool
class_name ProscenioParseHelpers extends Resource

# Tiny helper module pulled in by the generated Resource classes.
# Lives here so the per-class from_dict snippets stay short.


static func _parse_vec2_array(raw: Array) -> Array[PackedFloat32Array]:
	var out: Array[PackedFloat32Array] = []
	for item in raw:
		out.append(PackedFloat32Array(item))
	return out


static func _parse_int_array(raw: Array) -> Array[PackedInt32Array]:
	var out: Array[PackedInt32Array] = []
	for item in raw:
		out.append(PackedInt32Array(item))
	return out


static func _parse_array(klass, raw: Array) -> Array:
	var out: Array = []
	for item in raw:
		out.append(klass.from_dict(item))
	return out


static func _parse_dispatched(dispatcher, raw: Array) -> Array:
	var out: Array = []
	for item in raw:
		out.append(dispatcher.from_dict(item))
	return out
