// AUTO-GENERATED by proscenio-codegen from packages/models/.
// Do not edit by hand; edit the pydantic models and re-run
// `python -m proscenio_codegen ts`.


/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Animations = Animation[] | null;
export type Length = number;
export type Loop = boolean | null;
export type Name = string;
export type Attachment = string | null;
export type Frame = number | null;
export type Interp = ("linear" | "constant") | null;
export type Position = [number, number] | null;
export type Rotation = number | null;
export type Scale = [number, number] | null;
export type Time = number;
export type Visible = boolean | null;
export type Keys = Key[];
export type Target = string;
export type Type = "bone_transform" | "sprite_frame" | "slot_attachment" | "visibility";
export type Tracks = Track[];
export type Atlas = string | null;
/**
 * Bump on any breaking change to the shape of this document.
 */
export type FormatVersion = 1;
export type Name1 = string;
export type PixelsPerUnit = number;
export type Length1 = number | null;
export type Name2 = string;
export type Parent = string | null;
export type Position1 = [number, number] | null;
export type Rotation1 = number | null;
export type Scale1 = [number, number] | null;
export type Bones = Bone[];
export type Slots = Slot[] | null;
export type Attachments = string[];
export type Bone1 = string | null;
export type Default = string | null;
export type Name3 = string;
export type Bone2 = string | null;
export type Name4 = string;
export type Polygon = [number, number][];
/**
 * Optional per-sprite texture filename, resolved relative to the .proscenio document. Multi-PNG fixtures use this so each sprite picks its own image instead of slicing a shared atlas. Importers fall back to the top-level `atlas` field when absent.
 */
export type Texture = string | null;
/**
 * [x, y, width, height] in atlas pixels.
 *
 * @minItems 4
 * @maxItems 4
 */
export type TextureRegion = [number, number, number, number];
/**
 * Discriminator. Optional; absence means `polygon`.
 */
export type Type1 = "polygon";
export type Uv = [number, number][];
export type Weights = Weight[] | null;
export type Bone3 = string;
export type Values = number[];
export type Bone4 = string;
export type Centered = boolean;
/**
 * Initial frame index (row-major). Animation tracks override at runtime.
 */
export type Frame1 = number;
export type Hframes = number;
export type Name5 = string;
/**
 * @minItems 2
 * @maxItems 2
 */
export type Offset = [number, number];
/**
 * Optional per-sprite texture filename, resolved relative to the .proscenio document. Mirrors the polygon-sprite field. Importers fall back to the top-level `atlas` field when absent.
 */
export type Texture1 = string | null;
/**
 * Optional sub-rectangle within the atlas where the spritesheet lives. Absent means use the full atlas.
 */
export type TextureRegion1 = [number, number, number, number] | null;
/**
 * Discriminator. Required and constant.
 */
export type Type2 = "sprite_frame";
export type Vframes = number;
export type Sprites = (PolygonSprite | SpriteFrameSprite)[];

/**
 * Root of a .proscenio v1 document.
 *
 * Schema id mirrors the hand-maintained file so consumer ajv
 * validators that key off ``$id`` continue to resolve.
 */
export interface ProscenioCharacter {
  animations?: Animations;
  atlas?: Atlas;
  format_version: FormatVersion;
  name: Name1;
  pixels_per_unit: PixelsPerUnit;
  skeleton: Skeleton;
  slots?: Slots;
  sprites: Sprites;
}
export interface Animation {
  length: Length;
  loop?: Loop;
  name: Name;
  tracks: Tracks;
}
export interface Track {
  keys: Keys;
  target: Target;
  type: Type;
}
export interface Key {
  attachment?: Attachment;
  frame?: Frame;
  interp?: Interp;
  position?: Position;
  rotation?: Rotation;
  scale?: Scale;
  time: Time;
  visible?: Visible;
}
export interface Skeleton {
  bones: Bones;
}
export interface Bone {
  length?: Length1;
  name: Name2;
  parent?: Parent;
  position?: Position1;
  rotation?: Rotation1;
  scale?: Scale1;
}
export interface Slot {
  attachments: Attachments;
  bone?: Bone1;
  default?: Default;
  name: Name3;
}
/**
 * Cutout-style sprite rendered as a Godot Polygon2D - vertices + UV.
 *
 * Default sprite kind when ``type`` is omitted (backwards-compatible
 * with v1 documents).
 *
 * Field declaration order mirrors the writer's dict insertion order
 * so ``model_dump_json(exclude_unset=True)`` reproduces the golden
 * fixtures byte-for-byte once the writer migrates.
 */
export interface PolygonSprite {
  bone?: Bone2;
  name: Name4;
  polygon: Polygon;
  texture?: Texture;
  texture_region: TextureRegion;
  type?: Type1;
  uv: Uv;
  weights?: Weights;
}
export interface Weight {
  bone: Bone3;
  values: Values;
}
/**
 * Spritesheet sprite rendered as a Godot Sprite2D.
 *
 * ``frame`` indexes into an ``hframes`` x ``vframes`` grid carved
 * out of the atlas (or out of ``texture_region`` when present).
 *
 * Field declaration order mirrors the writer's dict insertion order
 * so ``model_dump_json(exclude_unset=True)`` reproduces the golden
 * fixtures byte-for-byte once the writer migrates.
 */
export interface SpriteFrameSprite {
  bone: Bone4;
  centered?: Centered;
  frame?: Frame1;
  hframes: Hframes;
  name: Name5;
  offset?: Offset;
  texture?: Texture1;
  texture_region?: TextureRegion1;
  type: Type2;
  vframes: Vframes;
}
