// AUTO-GENERATED by proscenio-codegen from packages/models/.
// Do not edit by hand; edit the pydantic models and re-run
// `python -m proscenio_codegen ts`.


/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Animations = Animation[] | null;
export type Length = number;
export type Loop = boolean | null;
export type Name = string;
export type Attachment = string | null;
export type Frame = number | null;
export type Interp = ("linear" | "constant") | null;
export type Position = [number, number] | null;
export type Rotation = number | null;
export type Scale = [number, number] | null;
export type Time = number;
export type Keys = Key[];
export type Target = string;
export type Type = "bone_transform" | "sprite_frame" | "slot_attachment";
export type Tracks = Track[];
export type Atlas = string | null;
export type Bone = string | null;
/**
 * Optional RGBA tint, mirroring Godot's CanvasItem.modulate. Absent means opaque white (no tint). Additive at format_version 1.
 */
export type Modulate = [number, number, number, number] | null;
export type Name1 = string;
export type Polygon = [number, number][];
/**
 * Optional per-face vertex-index arrays into `polygon` / `uv`, mirroring Godot's Polygon2D.polygons. Present only for multi-face meshes (automesh output); absent means the single `polygon` ring is the whole element. Additive at format_version 1 - an importer that ignores it still renders the outline.
 */
export type Polygons = number[][] | null;
/**
 * Optional per-element texture filename, resolved relative to the .proscenio document. Multi-PNG fixtures use this so each element picks its own image instead of slicing a shared atlas. Importers fall back to the top-level `atlas` field when absent.
 */
export type Texture = string | null;
/**
 * [x, y, width, height] in atlas pixels.
 *
 * @minItems 4
 * @maxItems 4
 */
export type TextureRegion = [number, number, number, number];
/**
 * Discriminator. Optional; absence means `mesh`.
 */
export type Type1 = "mesh";
export type Uv = [number, number][];
export type Weights = Weight[] | null;
export type Bone1 = string;
export type Values = number[];
/**
 * Optional draw order, mirroring Godot's CanvasItem.z_index. Absent means 0. Carries the authored layer stacking the writer would otherwise drop. Additive at format_version 1.
 */
export type ZIndex = number | null;
export type Bone2 = string;
export type Centered = boolean;
/**
 * Optional horizontal flip, mirroring Godot's Sprite2D.flip_h. Absent means false. Additive at format_version 1.
 */
export type FlipH = boolean | null;
/**
 * Optional vertical flip, mirroring Godot's Sprite2D.flip_v. Absent means false. Additive at format_version 1.
 */
export type FlipV = boolean | null;
/**
 * Initial frame index (row-major). Animation tracks override at runtime.
 */
export type Frame1 = number;
export type Hframes = number;
/**
 * Optional RGBA tint, mirroring Godot's CanvasItem.modulate. Absent means opaque white (no tint). Additive at format_version 1.
 */
export type Modulate1 = [number, number, number, number] | null;
export type Name2 = string;
/**
 * @minItems 2
 * @maxItems 2
 */
export type Offset = [number, number];
/**
 * Optional per-element texture filename, resolved relative to the .proscenio document. Mirrors the mesh-element field. Importers fall back to the top-level `atlas` field when absent.
 */
export type Texture1 = string | null;
/**
 * Optional sub-rectangle within the atlas where the spritesheet lives. Absent means use the full atlas.
 */
export type TextureRegion1 = [number, number, number, number] | null;
/**
 * Discriminator. Required and constant.
 */
export type Type2 = "sprite";
export type Vframes = number;
/**
 * Optional draw order, mirroring Godot's CanvasItem.z_index. Absent means 0. Additive at format_version 1.
 */
export type ZIndex1 = number | null;
export type Elements = (MeshElement | SpriteElement)[];
/**
 * Bump on any breaking change to the shape of this document.
 */
export type FormatVersion = 1;
export type Name3 = string;
export type PixelsPerUnit = number;
export type Length1 = number | null;
export type Name4 = string;
export type Parent = string | null;
export type Position1 = [number, number] | null;
export type Rotation1 = number | null;
export type Scale1 = [number, number] | null;
export type Bones = Bone3[];
export type Slots = Slot[] | null;
export type Attachments = string[];
export type Bone4 = string | null;
export type Default = string | null;
export type Name5 = string;

/**
 * Root of a .proscenio v1 document.
 *
 * Schema id mirrors the hand-maintained file so consumer ajv
 * validators that key off ``$id`` continue to resolve.
 */
export interface ProscenioCharacter {
  animations?: Animations;
  atlas?: Atlas;
  elements: Elements;
  format_version: FormatVersion;
  name: Name3;
  pixels_per_unit: PixelsPerUnit;
  skeleton: Skeleton;
  slots?: Slots;
}
export interface Animation {
  length: Length;
  loop?: Loop;
  name: Name;
  tracks: Tracks;
}
export interface Track {
  keys: Keys;
  target: Target;
  type: Type;
}
export interface Key {
  attachment?: Attachment;
  frame?: Frame;
  interp?: Interp;
  position?: Position;
  rotation?: Rotation;
  scale?: Scale;
  time: Time;
}
/**
 * Deformable cutout element rendered as a Godot Polygon2D - vertices + UV.
 *
 * Default element kind when ``type`` is omitted. Field order reproduces
 * the goldens.
 */
export interface MeshElement {
  bone?: Bone;
  modulate?: Modulate;
  name: Name1;
  polygon: Polygon;
  polygons?: Polygons;
  texture?: Texture;
  texture_region: TextureRegion;
  type?: Type1;
  uv: Uv;
  weights?: Weights;
  z_index?: ZIndex;
}
export interface Weight {
  bone: Bone1;
  values: Values;
}
/**
 * Rigid sprite rendered as a Godot Sprite2D.
 *
 * ``frame`` indexes into an ``hframes`` x ``vframes`` grid carved
 * out of the atlas (or out of ``texture_region`` when present). A
 * single-frame sprite (``hframes`` = ``vframes`` = 1) is the static
 * case. Field order reproduces the goldens.
 */
export interface SpriteElement {
  bone: Bone2;
  centered?: Centered;
  flip_h?: FlipH;
  flip_v?: FlipV;
  frame?: Frame1;
  hframes: Hframes;
  modulate?: Modulate1;
  name: Name2;
  offset?: Offset;
  texture?: Texture1;
  texture_region?: TextureRegion1;
  type: Type2;
  vframes: Vframes;
  z_index?: ZIndex1;
}
export interface Skeleton {
  bones: Bones;
}
export interface Bone3 {
  length?: Length1;
  name: Name4;
  parent?: Parent;
  position?: Position1;
  rotation?: Rotation1;
  scale?: Scale1;
}
export interface Slot {
  attachments: Attachments;
  bone?: Bone4;
  default?: Default;
  name: Name5;
}
