// AUTO-GENERATED by proscenio-codegen from packages/models/.
// Do not edit by hand; edit the pydantic models and re-run
// `python -m proscenio_codegen ts`.


/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Document anchor in PSD pixels. Set by the first horizontal + vertical PSD guide; importer places the root bone here. Omitted when no guides were authored.
 */
export type Anchor = [number, number] | null;
/**
 * Original PSD filename. Display only - not a resolvable path.
 */
export type Doc = string;
/**
 * Bump on any breaking change to the shape of this document. v2 introduces the tag-driven taxonomy in the photoshop tag system (anchor, per-entry origin, blend_mode, subfolder, kind: "mesh").
 */
export type FormatVersion = 2;
/**
 * Layer blend mode emitted from the PSD; importer maps to material blend mode.
 */
export type BlendMode = ("normal" | "multiply" | "screen" | "additive") | null;
export type Kind = "polygon" | "mesh";
export type Name = string;
/**
 * Optional pivot in PSD pixels. Set by the [origin:x,y] tag or by an [origin] marker layer inside the group. Importer uses this as the mesh's Object.location when present; falls back to bbox center otherwise.
 */
export type Origin = [number, number] | null;
/**
 * Path to the layer PNG, relative to the manifest file.
 */
export type Path = string;
/**
 * PSD top-left bbox of the layer in pixels.
 *
 * @minItems 2
 * @maxItems 2
 */
export type Position = [number, number];
/**
 * Layer bbox size in pixels.
 *
 * @minItems 2
 * @maxItems 2
 */
export type Size = [number, number];
/**
 * Optional output sub-folder under images/, set by the [folder:name] tag. Importer ignores; this is purely a disk-layout hint reflected in `path`.
 */
export type Subfolder = string | null;
/**
 * Stack index, 0 = top.
 */
export type ZOrder = number;
export type BlendMode1 = ("normal" | "multiply" | "screen" | "additive") | null;
/**
 * @minItems 2
 */
export type Frames = [FrameEntry, FrameEntry, ...FrameEntry[]];
/**
 * Frame index, 0-based, contiguous, ordered.
 */
export type Index = number;
/**
 * Path to the frame PNG, relative to the manifest file.
 */
export type Path1 = string;
export type Kind1 = "sprite_frame";
export type Name1 = string;
/**
 * Optional pivot in PSD pixels (see polygon_layer.origin).
 */
export type Origin1 = [number, number] | null;
/**
 * PSD top-left bbox of the largest frame.
 *
 * @minItems 2
 * @maxItems 2
 */
export type Position1 = [number, number];
/**
 * Largest frame bbox size in pixels (importer pads smaller frames to match).
 *
 * @minItems 2
 * @maxItems 2
 */
export type Size1 = [number, number];
export type Subfolder1 = string | null;
export type ZOrder1 = number;
/**
 * Z-ordered top-to-bottom. Each entry is a single mesh in Blender after import.
 */
export type Layers = (PolygonLayer | SpriteFrameLayer)[];
/**
 * Importer divides PSD pixels by this when stamping mesh size and position.
 */
export type PixelsPerUnit = number;
/**
 * [doc_width_px, doc_height_px].
 *
 * @minItems 2
 * @maxItems 2
 */
export type Size2 = [number, number];

/**
 * Root of a PSD manifest v2 document.
 */
export interface ProscenioPSDManifest {
  anchor?: Anchor;
  doc: Doc;
  format_version: FormatVersion;
  layers: Layers;
  pixels_per_unit: PixelsPerUnit;
  size: Size2;
}
/**
 * Single PNG, single quad mesh.
 *
 * ``kind: "mesh"`` is a polygon superset flagged as a deformable mesh
 * source; renders as polygon when no rig is bound.
 */
export interface PolygonLayer {
  blend_mode?: BlendMode;
  kind: Kind;
  name: Name;
  origin?: Origin;
  path: Path;
  position: Position;
  size: Size;
  subfolder?: Subfolder;
  z_order: ZOrder;
}
/**
 * N frames, single quad mesh, animated via ``proscenio.frame``.
 *
 * Authored as a LayerSet tagged ``[spritesheet]``.
 */
export interface SpriteFrameLayer {
  blend_mode?: BlendMode1;
  frames: Frames;
  kind: Kind1;
  name: Name1;
  origin?: Origin1;
  position: Position1;
  size: Size1;
  subfolder?: Subfolder1;
  z_order: ZOrder1;
}
export interface FrameEntry {
  index: Index;
  path: Path1;
}
