import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Three navbar sections off the same docs instance, sliced by audience:
//   - guidesSidebar: the hand-written tutorials (Basic / Advanced) for the artist.
//   - projectSidebar: low-level docs for devs - Architecture / Comparison /
//     Deferred, then the live schema reference under content/ (grouped as Schema).
//   - toolsSidebar: high-level, intent-level reference per app (Blender Addon,
//     Photoshop Plugin, Godot Plugin).
//
// Each area is a category whose `link` is the area's index.md, so that page is
// the category's landing rather than a stray sibling leaf. Docusaurus emits the
// root index of an autogenerated dirName as a duplicate leaf even with `link`
// set; docusaurus.config.ts's sidebarItemsGenerator strips those (its
// SECTION_LANDING_IDS must list every root-index id linked below that also sits
// inside an autogenerated dirName: guides/index, project/index, content/README).
const sidebars: SidebarsConfig = {
  guidesSidebar: [
    'README',
    {
      type: 'category',
      label: 'Guides',
      link: {type: 'doc', id: 'guides/index'},
      items: [{type: 'autogenerated', dirName: '00-guides'}],
    },
  ],

  projectSidebar: [
    {
      type: 'category',
      label: 'Project',
      link: {type: 'doc', id: 'project/index'},
      collapsed: false,
      items: [{type: 'autogenerated', dirName: '01-project'}],
    },
    {
      type: 'category',
      label: 'Schema',
      link: {type: 'doc', id: 'content/README'},
      items: [{type: 'autogenerated', dirName: 'content'}],
    },
  ],

  toolsSidebar: [
    {
      type: 'category',
      label: 'Tools',
      link: {type: 'doc', id: 'tools/index'},
      collapsed: false,
      items: [
        {
          // The panels are listed explicitly (not autogenerated) so the overview
          // page can serve as the category link without also appearing as a child.
          // Keep this in NN-prefix order; add new panels here when they land.
          type: 'category',
          label: 'Blender Addon',
          link: {type: 'doc', id: 'tools/blender-addon/index'},
          collapsed: false,
          items: [
            'tools/blender-addon/outliner',
            'tools/blender-addon/element',
            'tools/blender-addon/slots',
            'tools/blender-addon/skeleton',
            'tools/blender-addon/mesh-generation',
            'tools/blender-addon/weight-paint',
            'tools/blender-addon/animation',
            'tools/blender-addon/atlas',
            'tools/blender-addon/pipeline',
            'tools/blender-addon/helpers',
          ],
        },
        {type: 'autogenerated', dirName: '02-tools/photoshop-plugin'},
        {type: 'autogenerated', dirName: '02-tools/godot-plugin'},
      ],
    },
  ],
};

export default sidebars;
