import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Two sidebars off the same docs instance, to keep hand-authored guides visibly
// separate from the codegen schema reference:
//   - guidesSidebar: the hand-written docs at the docs/ root (explicit list, so
//     the generated content/ subtree never leaks in).
//   - apiSidebar: the live-rendered schema reference under content/, autogenerated.
const sidebars: SidebarsConfig = {
  guidesSidebar: [
    'README',
    {
      type: 'category',
      label: 'Workflows',
      items: [
        'WALKTHROUGH',
        'PHOTOSHOP-WORKFLOW',
        'BLENDER-WORKFLOW',
        'GODOT-WORKFLOW',
      ],
    },
    {
      type: 'category',
      label: 'Project',
      items: ['ARCHITECTURE', 'FEATURES', 'COMPARISON', 'DEFERRED'],
    },
  ],

  apiSidebar: [{type: 'autogenerated', dirName: 'content'}],
};

export default sidebars;
