import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Three navbar sections off the same docs instance, sliced by audience:
//   - guidesSidebar: the hand-written tutorials (Basic / Advanced) for the artist.
//   - projectSidebar: low-level docs for devs - the live schema reference under
//     content/ (grouped as Schema), then Architecture / Comparison / Deferred.
//   - toolsSidebar: high-level, intent-level reference per app (Blender Addon,
//     Photoshop Plugin, Godot Plugin).
const sidebars: SidebarsConfig = {
  guidesSidebar: [
    'README',
    {
      type: 'category',
      label: 'Guides',
      items: [{type: 'autogenerated', dirName: '00-guides'}],
    },
  ],

  projectSidebar: [
    {
      type: 'category',
      label: 'Schema',
      items: [{type: 'autogenerated', dirName: 'content'}],
    },
    {type: 'autogenerated', dirName: '01-project'},
  ],

  toolsSidebar: [
    {
      // The panels are listed explicitly (not autogenerated) so the overview
      // page can serve as the category link without also appearing as a child.
      // Keep this in NN-prefix order; add new panels here when they land.
      type: 'category',
      label: 'Blender Addon',
      link: {type: 'doc', id: 'blender-addon/index'},
      collapsed: false,
      items: [
        'blender-addon/outliner',
        'blender-addon/element',
        'blender-addon/slots',
        'blender-addon/skeleton',
        'blender-addon/mesh-generation',
        'blender-addon/weight-paint',
        'blender-addon/animation',
        'blender-addon/atlas',
        'blender-addon/validation',
        'blender-addon/pipeline',
        'blender-addon/helpers',
      ],
    },
    {type: 'autogenerated', dirName: '03-photoshop-plugin'},
    {type: 'autogenerated', dirName: '04-godot-plugin'},
  ],
};

export default sidebars;
