"""Shared I/O helpers for the codegen emitters.

Provides:

- ``REPO_ROOT`` resolution from this file's location;
- ``write_atomic`` that writes through a temp file and renames so a
  half-finished emit cannot leave a truncated artifact behind;
- ``AUTO_GENERATED_BANNER`` for the language-agnostic header. Each
  emitter wraps it in the comment syntax of its target language.
"""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path

# packages/codegen/src/proscenio_codegen/_io.py
#   parents[0]=proscenio_codegen [1]=src [2]=codegen [3]=packages [4]=repo
REPO_ROOT = Path(__file__).resolve().parents[4]

AUTO_GENERATED_BANNER = (
    "AUTO-GENERATED by proscenio-codegen from packages/models/. "
    "Do not edit by hand; edit the pydantic models and re-run "
    "`python -m proscenio_codegen <emitter>`."
)


def write_atomic(target: Path, payload: str) -> None:
    """Write ``payload`` to ``target`` via a temp file + rename.

    A half-finished emit (interrupted by ctrl-C, disk full, etc.)
    cannot leave a truncated artifact behind; either the rename
    happens or the file stays unchanged.
    """
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(
        prefix=f".{target.name}.",
        suffix=".tmp",
        dir=str(target.parent),
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(payload)
        os.replace(tmp_name, target)
    except Exception:
        try:
            os.unlink(tmp_name)
        except OSError:
            # Swallow the cleanup error so the original failure propagates.
            pass
        raise


def dumps_json(payload: object) -> str:
    """Serialize ``payload`` as JSON with the project's canonical shape.

    Two-space indent, sorted keys, trailing newline. Pinned so the
    file is reproducible across machines and the staleness check in
    CI is meaningful (a non-empty ``git status`` after re-emit means
    drift, not formatter noise).
    """
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"
