"""GDScript ``Resource`` emitter.

Walks the pydantic models in ``proscenio_models`` and emits a typed
``Resource`` subclass per ``BaseModel`` under
``apps/godot/addons/proscenio/schema_bindings/``. Each generated file
carries an AUTO-GENERATED header, declares ``@export`` properties for
every field, and ships a ``from_dict`` static factory that parses a
JSON-decoded Dictionary into the typed instance.

Discriminated unions become a thin dispatcher class whose ``from_dict``
inspects the discriminator key and delegates to the concrete variant.

Type mapping (pydantic -> GDScript):

- ``int``                -> ``int``
- ``float``              -> ``float``
- ``str``                -> ``String``
- ``bool``               -> ``bool``
- ``Literal[...]``       -> ``String`` or ``int`` (the literal type)
- ``list[Vec2]``         -> ``PackedVector2Array``
- ``list[float]``        -> ``PackedFloat32Array`` (also Vec2/Rect)
- ``list[X]`` (BaseModel)-> ``Array[X]`` (typed array)
- ``list[str]``          -> ``PackedStringArray``
- ``X | None``           -> nullable; the from_dict handles the absence
"""

from __future__ import annotations

import inspect
import shutil
import subprocess
import types
import typing
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal, Union, get_args, get_origin

from pydantic import BaseModel
from pydantic.fields import FieldInfo

from proscenio_codegen._io import REPO_ROOT, write_atomic

GODOT_BINDINGS_DIR = (
    REPO_ROOT / "apps" / "godot" / "addons" / "proscenio" / "schema_bindings"
)

_AUTO_HEADER = (
    "# AUTO-GENERATED by proscenio-codegen from packages/models/.\n"
    "# Do not edit by hand; edit the pydantic models and re-run\n"
    "# `python -m proscenio_codegen godot`.\n"
)


@dataclass(frozen=True)
class _ResolvedType:
    """A field's mapped GDScript type plus the parser snippet."""

    gd_type: str
    """The annotation string used after ``var name :``."""

    default: str
    """The literal default used after ``=``."""

    parse_expr_template: str
    """Format string with one placeholder ``{value}`` that wraps the raw
    Dictionary lookup so the parsed value matches ``gd_type``."""

    needs_assign: bool = False
    """When True, emit ``res.field.assign(<parsed>)`` instead of
    ``res.field = <parsed>``. The object and union array parsers return an
    untyped ``Array``; assigning that straight into a typed ``Array[T]``
    property is rejected at runtime, so the typed array is filled via
    ``Array.assign`` which copies element-wise with conversion."""


def _is_vec_like(args: tuple[Any, ...]) -> bool:
    """A ``list[float]`` annotation (used by Vec2, Rect, list[Vec2] items)."""
    return len(args) == 1 and args[0] is float


_PACKED_SCALAR: dict[type, tuple[str, str]] = {
    float: ("PackedFloat32Array", "PackedFloat32Array"),
    str: ("PackedStringArray", "PackedStringArray"),
    int: ("PackedInt32Array", "PackedInt32Array"),
}

_PARSE_INT = "int({value})"
_PARSE_FLOAT = "float({value})"
_PARSE_STRING = "String({value})"
_PARSE_BOOL = "bool({value})"


def _peel_annotated(annotation: Any) -> Any:
    """Strip every ``Annotated[T, ...]`` wrapper layer off ``annotation``."""
    while (
        get_origin(annotation) is typing.Annotated
        or getattr(annotation.__class__, "__name__", "") == "_AnnotatedAlias"
    ):
        annotation = get_args(annotation)[0]
    return annotation


def _union_dispatcher_name(item: Any) -> str | None:
    """If ``item`` is a tagged discriminated union, return its dispatcher.

    Lookup table keyed by the set of concrete BaseModel variants in the
    Union. Each Annotated[BaseModel, Tag] inside the union unwraps to a
    plain BaseModel; we read the set of those and map to the GDScript
    dispatcher class emitted alongside the per-variant resources.
    """
    origin = get_origin(item)
    if origin not in (Union, types.UnionType):
        return None
    variant_models: set[type[BaseModel]] = set()
    for variant in get_args(item):
        peeled = _peel_annotated(variant)
        if isinstance(peeled, type) and issubclass(peeled, BaseModel):
            variant_models.add(peeled)
    if not variant_models:
        return None
    from proscenio_models.proscenio import MeshElement, SpriteElement
    from proscenio_models.psd_manifest import MeshLayer, SpriteLayer

    # Typed as the same set element type as `variant_models` so the literal
    # joins to `type[BaseModel]` rather than the per-module `_Strict` base
    # (proscenio and psd_manifest each define one; the bare literal would
    # join to the wrong one and fail the equality check under strict mypy).
    element_variants: set[type[BaseModel]] = {MeshElement, SpriteElement}
    layer_variants: set[type[BaseModel]] = {MeshLayer, SpriteLayer}
    if variant_models == element_variants:
        return "ProscenioElement"
    if variant_models == layer_variants:
        return "ProscenioLayer"
    return None


def _resolve_list_type(item: Any) -> _ResolvedType:
    """Resolve the element type inside a ``list[item]`` annotation."""
    item = _peel_annotated(item)

    packed = _PACKED_SCALAR.get(item)
    if packed is not None:
        gd_type, ctor = packed
        return _ResolvedType(gd_type, f"{ctor}()", f"{ctor}({{value}})")

    nested_origin = get_origin(item)
    nested_args = get_args(item)
    if nested_origin in (list, typing.List) and _is_vec_like(nested_args):
        return _ResolvedType(
            "Array[PackedFloat32Array]",
            "[] as Array[PackedFloat32Array]",
            "ProscenioParseHelpers._parse_vec2_array({value})",
        )
    if nested_origin in (list, typing.List) and nested_args == (int,):
        return _ResolvedType(
            "Array[PackedInt32Array]",
            "[] as Array[PackedInt32Array]",
            "ProscenioParseHelpers._parse_int_array({value})",
        )
    dispatcher = _union_dispatcher_name(item)
    if dispatcher is not None:
        return _ResolvedType(
            f"Array[{dispatcher}]",
            f"[] as Array[{dispatcher}]",
            f"ProscenioParseHelpers._parse_dispatched({dispatcher}, {{value}})",
            needs_assign=True,
        )
    if isinstance(item, type) and issubclass(item, BaseModel):
        class_name = _resource_class_name(item)
        return _ResolvedType(
            f"Array[{class_name}]",
            f"[] as Array[{class_name}]",
            f"ProscenioParseHelpers._parse_array({class_name}, {{value}})",
            needs_assign=True,
        )

    raise NotImplementedError(f"godot_emit cannot map list[{item!r}]")


_SCALAR_MAP: dict[type, _ResolvedType] = {
    int: _ResolvedType("int", "0", _PARSE_INT),
    float: _ResolvedType("float", "0.0", _PARSE_FLOAT),
    str: _ResolvedType("String", '""', _PARSE_STRING),
    bool: _ResolvedType("bool", "false", _PARSE_BOOL),
}


def _resolve_literal(args: tuple[Any, ...]) -> _ResolvedType | None:
    """Return the GDScript mapping for ``Literal[sample, ...]``."""
    sample = args[0]
    # bool check first: isinstance(True, int) is True, so int branch would
    # swallow the bool variant otherwise.
    if isinstance(sample, bool):
        return _ResolvedType("bool", str(sample).lower(), _PARSE_BOOL)
    if isinstance(sample, str):
        return _ResolvedType("String", f'"{sample}"', _PARSE_STRING)
    if isinstance(sample, int):
        return _ResolvedType("int", str(sample), _PARSE_INT)
    return None


def _is_annotated(annotation: Any, origin: Any) -> bool:
    """Whether ``annotation`` is an ``Annotated[...]`` wrapper."""
    if origin is typing.Annotated:
        return True
    return getattr(annotation.__class__, "__name__", "") == "_AnnotatedAlias"


def _resolve_union(args: tuple[Any, ...]) -> _ResolvedType:
    """Unwrap ``Optional[X]`` / ``X | None`` to its inner type."""
    non_none = [a for a in args if a is not type(None)]
    if len(non_none) != 1:
        raise NotImplementedError(f"godot_emit cannot map Union[{args!r}]")
    return _resolve_type(non_none[0])


def _resolve_basemodel(annotation: type[BaseModel]) -> _ResolvedType:
    """Resolve a nested pydantic model reference."""
    class_name = _resource_class_name(annotation)
    return _ResolvedType(class_name, "null", f"{class_name}.from_dict({{value}})")


def _resolve_type(annotation: Any) -> _ResolvedType:
    """Map a pydantic field annotation to its GDScript counterpart."""
    origin = get_origin(annotation)
    args = get_args(annotation)

    if _is_annotated(annotation, origin):
        return _resolve_type(args[0])
    if origin in (Union, types.UnionType):
        return _resolve_union(args)
    if origin is Literal:
        resolved = _resolve_literal(args)
        if resolved is not None:
            return resolved
    scalar = _SCALAR_MAP.get(annotation)
    if scalar is not None:
        return scalar
    if origin in (list, typing.List):
        (item,) = args
        return _resolve_list_type(item)
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return _resolve_basemodel(annotation)
    raise NotImplementedError(
        f"godot_emit cannot map annotation {annotation!r} (origin={origin}, args={args})"
    )


def _resource_class_name(model: type[BaseModel]) -> str:
    """The GDScript ``class_name`` derived from a pydantic class.

    Every generated class gets a ``Proscenio`` prefix so it cannot
    collide with Godot's built-in classes (``Animation``, ``Skeleton``,
    ``Bone`` would all shadow native types otherwise). Models already
    prefixed ``Proscenio`` keep their name.
    """
    name = model.__name__
    if name.startswith("Proscenio"):
        return name
    return f"Proscenio{name}"


def _filename(model: type[BaseModel]) -> str:
    """The on-disk filename for a model's emitted .gd file (snake_case).

    Derived from the prefixed class_name so files and globals stay in
    one-to-one correspondence (``ProscenioBone`` -> ``proscenio_bone.gd``).
    """
    name = _resource_class_name(model)
    out: list[str] = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0:
            out.append("_")
        out.append(ch.lower())
    return "".join(out) + ".gd"


def _python_default(field: FieldInfo) -> Any:
    """Best-effort extraction of the default value declared on a pydantic field."""
    if (
        field.default is not None
        and field.default.__class__.__name__ != "PydanticUndefinedType"
    ):
        return field.default
    factory = getattr(field, "default_factory", None)
    if factory is not None:
        try:
            return factory()
        except Exception:
            return None
    return None


def _variant_dispatcher(model: type[BaseModel]) -> str | None:
    """The dispatcher class a variant should extend, or None if none.

    Lets ``Array[ProscenioElement]`` actually hold ``MeshElement`` and
    ``SpriteElement`` instances via runtime polymorphism. Without
    the inheritance, GDScript's typed-array runtime check refuses any
    instance whose class is not the exact element type.
    """
    from proscenio_models.proscenio import MeshElement, SpriteElement
    from proscenio_models.psd_manifest import MeshLayer, SpriteLayer

    if model in (MeshElement, SpriteElement):
        return "ProscenioElement"
    if model in (MeshLayer, SpriteLayer):
        return "ProscenioLayer"
    return None


def _emit_model(model: type[BaseModel]) -> str:
    """Build the GDScript text for a single pydantic model."""
    class_name = _resource_class_name(model)
    parent = _variant_dispatcher(model) or "Resource"
    fields = model.model_fields
    lines: list[str] = [
        _AUTO_HEADER,
        "@tool",
        f"class_name {class_name} extends {parent}",
        "",
    ]

    field_decls: list[str] = [
        "# Names of fields actually set during `from_dict`. Lets consumers",
        "# distinguish 'field set to default' from 'field absent in source'",
        "# without re-parsing the JSON dictionary.",
        "@export var _set_fields: PackedStringArray = PackedStringArray()",
    ]
    parsers: list[str] = []

    for name, field in fields.items():
        resolved = _resolve_type(field.annotation)
        default = resolved.default

        py_default = _python_default(field)
        if isinstance(py_default, list) and resolved.gd_type == "PackedFloat32Array":
            joined = ", ".join(f"{v}" for v in py_default)
            default = f"PackedFloat32Array([{joined}])"

        field_decls.append(f"@export var {name}: {resolved.gd_type} = {default}")

        wrapped = resolved.parse_expr_template.format(value=f'data["{name}"]')
        # Typed-array properties (Array[T]) cannot take the untyped Array the
        # object/union parsers return via plain ``=``; fill them with
        # ``Array.assign`` instead.
        assignment = (
            f"res.{name}.assign({wrapped})"
            if resolved.needs_assign
            else f"res.{name} = {wrapped}"
        )
        # Guard against JSON nulls: pydantic Optional fields decode as None,
        # which would break String(null) / Vector2(null) parsers; the
        # property default covers the missing case.
        parsers.append(
            f'\tif data.has("{name}") and data["{name}"] != null:\n'
            f"\t\t{assignment}\n"
            f'\t\tres._set_fields.append("{name}")\n'
        )

    lines.extend(field_decls)
    lines.append("")
    lines.append("")
    lines.append(f"static func from_dict(data: Dictionary) -> {class_name}:")
    lines.append(f"\tvar res := {class_name}.new()")
    lines.extend(p.rstrip("\n") for p in parsers)
    lines.append("\treturn res")
    lines.append("")

    return "\n".join(lines)


def _emit_union_dispatcher(
    base_name: str,
    discriminator_field: str,
    variants: dict[str, type[BaseModel]],
) -> str:
    """Build the GDScript text for a discriminated-union dispatcher."""
    lines: list[str] = [
        _AUTO_HEADER,
        "@tool",
        f"class_name {base_name} extends Resource",
        "",
        "# Discriminated union dispatcher. Inspect the input dictionary's",
        f"# `{discriminator_field}` key and delegate to the matching variant",
        "# class. Used by the importer when building child elements/layers from",
        "# the parsed JSON document.",
        "",
    ]

    cases: list[str] = []
    for tag, variant_model in variants.items():
        variant_class = _resource_class_name(variant_model)
        cases.append(
            f'\tif tag == "{tag}":\n\t\treturn {variant_class}.from_dict(data)'
        )

    lines.append(f"static func from_dict(data: Dictionary) -> {base_name}:")
    if discriminator_field == "type":
        # Element discriminator: the mesh variant allows the field to be
        # absent (type omitted). Default to the mesh tag.
        default_tag = next(
            (
                t
                for t, m in variants.items()
                if any(f.default == t for f in m.model_fields.values())
            ),
            "",
        )
        lines.append(
            f'\tvar tag: String = String(data.get("{discriminator_field}", "{default_tag}"))'
        )
    else:
        lines.append(
            f'\tvar tag: String = String(data.get("{discriminator_field}", ""))'
        )
    lines.extend(c.rstrip("\n") for c in cases)
    lines.append('\tpush_error("unknown ' + base_name + ' tag: " + tag)')
    lines.append("\treturn null")
    lines.append("")

    return "\n".join(lines)


def _build_helper(signature: str, accumulator: str, append_expr: str) -> str:
    """Render one parsing helper as a multi-line GDScript snippet."""
    return (
        f"{signature}\n"
        f"\t{accumulator}\n"
        "\tfor item in raw:\n"
        f"\t\tout.append({append_expr})\n"
        "\treturn out\n"
    )


def _emit_helpers() -> str:
    """Common parsing helpers shared by every generated Resource class."""
    helpers = [
        _build_helper(
            "static func _parse_vec2_array(raw: Array) -> Array[PackedFloat32Array]:",
            "var out: Array[PackedFloat32Array] = []",
            "PackedFloat32Array(item)",
        ),
        _build_helper(
            "static func _parse_int_array(raw: Array) -> Array[PackedInt32Array]:",
            "var out: Array[PackedInt32Array] = []",
            "PackedInt32Array(item)",
        ),
        _build_helper(
            "static func _parse_array(klass, raw: Array) -> Array:",
            "var out: Array = []",
            "klass.from_dict(item)",
        ),
        _build_helper(
            "static func _parse_dispatched(dispatcher, raw: Array) -> Array:",
            "var out: Array = []",
            "dispatcher.from_dict(item)",
        ),
    ]
    return (
        f"{_AUTO_HEADER}@tool\n"
        "class_name ProscenioParseHelpers extends Resource\n"
        "\n"
        "# Tiny helper module pulled in by the generated Resource classes.\n"
        "# Lives here so the per-class from_dict snippets stay short.\n"
        "\n" + "\n".join(helpers)
    )


def _collect_models() -> list[type[BaseModel]]:
    """Every BaseModel class in proscenio_models that needs a .gd binding."""
    import proscenio_models

    models: list[type[BaseModel]] = []
    seen: set[type[BaseModel]] = set()
    for value in vars(proscenio_models).values():
        if (
            inspect.isclass(value)
            and issubclass(value, BaseModel)
            and value is not BaseModel
            and value not in seen
            and not value.__name__.startswith("_")
        ):
            seen.add(value)
            models.append(value)
    return models


def emit_godot_resources(target_dir: Path = GODOT_BINDINGS_DIR) -> list[Path]:
    """Emit one .gd file per pydantic model. Returns the written paths."""
    written: list[Path] = []

    helpers_target = target_dir / "proscenio_parse_helpers.gd"
    write_atomic(helpers_target, _emit_helpers())
    written.append(helpers_target)

    for model in _collect_models():
        text = _emit_model(model)
        target = target_dir / _filename(model)
        write_atomic(target, text)
        written.append(target)

    # Discriminated union dispatchers (Element, Layer). The unions themselves
    # are not BaseModel classes - they are Annotated[Union[...], Discriminator]
    # aliases - so they do not surface through _collect_models(); emit them
    # explicitly with the variants the models module exposes.
    from proscenio_models.proscenio import MeshElement, SpriteElement
    from proscenio_models.psd_manifest import MeshLayer, SpriteLayer

    element_dispatcher = _emit_union_dispatcher(
        "ProscenioElement",
        "type",
        {"mesh": MeshElement, "sprite": SpriteElement},
    )
    element_target = target_dir / "proscenio_element.gd"
    write_atomic(element_target, element_dispatcher)
    written.append(element_target)

    layer_dispatcher = _emit_union_dispatcher(
        "ProscenioLayer",
        "kind",
        {
            "mesh": MeshLayer,
            "sprite": SpriteLayer,
        },
    )
    layer_target = target_dir / "proscenio_layer.gd"
    write_atomic(layer_target, layer_dispatcher)
    written.append(layer_target)

    _gdformat_in_place(target_dir)

    return written


def _gdformat_in_place(target_dir: Path) -> None:
    """Run gdformat over the emitted files, if available.

    Matching gdformat's canonical shape (blank-line counts, trailing
    whitespace, indent) character-for-character from Python is brittle,
    so let gdformat re-write each file post-emit. When gdformat is not
    on PATH, skip silently - the gdscript-lint CI job is the staleness
    gate that catches drift.
    """
    binary = shutil.which("gdformat") or shutil.which("gdformat.exe")
    if binary is None:
        return
    subprocess.run([binary, str(target_dir)], check=False, capture_output=True)
