"""TypeScript interface emitter.

Invokes ``json-schema-to-typescript`` (npm) via subprocess against
every schema dumped under ``packages/models/schemas/`` and writes the
result to the per-app ``schema_bindings/`` folder under
``apps/photoshop/src/``.

The tool runs through ``npx --yes json-schema-to-typescript@<pin>`` so
contributors do not need a global install; pnpm and Node already exist
in the Photoshop dev setup. The pin matches the version recorded under
``apps/photoshop/package.json devDependencies`` so the generated
output is reproducible across machines.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from proscenio_codegen._io import REPO_ROOT, write_atomic

SCHEMAS_DIR = REPO_ROOT / "packages" / "models" / "schemas"
PHOTOSHOP_BINDINGS_DIR = REPO_ROOT / "apps" / "photoshop" / "src" / "schema_bindings"

# Pinned to match apps/photoshop/package.json devDependencies. Bump in
# both places together.
JSON_SCHEMA_TO_TYPESCRIPT_VERSION = "15.0.4"

_AUTO_HEADER = (
    "// AUTO-GENERATED by proscenio-codegen from packages/models/.\n"
    "// Do not edit by hand; edit the pydantic models and re-run\n"
    "// `python -m proscenio_codegen ts`.\n"
)


def _npx_executable() -> str:
    """Return the npx binary name; raise if Node is not installed."""
    npx = shutil.which("npx") or shutil.which("npx.cmd")
    if npx is None:
        raise RuntimeError(
            "ts_emit needs `npx` on PATH (Node.js + npm). Install Node, "
            "then re-run `python -m proscenio_codegen ts`."
        )
    return npx


def _run_json_schema_to_typescript(schema_path: Path) -> str:
    """Invoke the npm tool against ``schema_path`` and return the TS text."""
    npx = _npx_executable()
    result = subprocess.run(
        [
            npx,
            "--yes",
            f"json-schema-to-typescript@{JSON_SCHEMA_TO_TYPESCRIPT_VERSION}",
            "--no-additionalProperties",
            "--no-unreachableDefinitions",
            str(schema_path),
        ],
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return result.stdout


def emit_ts_bindings(
    schemas_dir: Path = SCHEMAS_DIR,
    bindings_dir: Path = PHOTOSHOP_BINDINGS_DIR,
) -> list[Path]:
    """Emit one ``.ts`` per schema under ``schemas_dir``.

    Returns the list of files written. Each output carries the
    AUTO-GENERATED header so a reader who lands in the binding file
    knows where the real source lives.
    """
    written: list[Path] = []
    for schema_path in sorted(schemas_dir.glob("*.schema.json")):
        ts_name = schema_path.stem.replace(".schema", "") + ".ts"
        target = bindings_dir / ts_name
        body = _run_json_schema_to_typescript(schema_path)
        # json-schema-to-typescript prepends `/* eslint-disable */`, but the
        # repo already excludes schema_bindings/ from the eslint run, so the
        # inline directive is redundant. Drop it so the committed binding stays
        # clean and the emit reproduces it byte-for-byte (the staleness gate).
        body = body.replace("/* eslint-disable */", "", 1)
        write_atomic(target, _AUTO_HEADER + "\n" + body)
        written.append(target)
    return written
